[data]
num_nodes = 6
num_node_features = 2

[model]
emb_size = 8
layer_num_g = 4

[training]
max_steps = 100
steps_per_epoch = 100
num_training_envs = 4
batch_size = 80 # batch_size that is a factor of steps_per_epoch * num_training_envs is recommended
epochs = 1e7

[rewards]
step_edge_correct = 0.5
step_edge_incorrect = -0.5
terminal_valid_score_multiplier = 20.0
terminal_invalid = -20.0

[debugging]
draw_graph = false
draw_correct_graphs = false
print_actions = false
print_extracted_features = false
