[data]
num_nodes = 6
num_node_features = 2

[model]
emb_size = 8
layer_num_g = 4

[training]
max_steps = 100
steps_per_epoch = 1000
epochs = 1e6

[rewards]
step_edge_correct = 1.0
step_edge_incorrect = -1.0
terminal_valid_score_multiplier = 20.0
terminal_invalid = -0.0

[debugging]
draw_graph = false
draw_correct_graphs = false
print_actions = false
print_extracted_features = false
