[data]
num_nodes = 10
num_node_features = 4

[model]
emb_size = 4
layer_num_g = 1

[training]
preconnect_nodes_probability = 0.25
max_steps = 150
steps_per_epoch = 4000
num_training_envs = 4
batch_size = 80 # batch_size that is a factor of steps_per_epoch * num_training_envs is recommended
epochs = 1e7

[rewards]
step_edge_correct = 0.5
step_edge_incorrect = -0.5
terminal_valid_score_multiplier = 20.0
score_min = 9 # 6n: 4, 20n: 28, 10: 9?
score_max = 26.5 # 6n: 13, 20n: 50, 10: 26.5?
terminal_invalid = -20.0

[debugging]
draw_graph = false
draw_correct_graphs = false
draw_preconnected_graphs = false
print_actions = false
print_extracted_features = false
